version: 'BETA {build}'
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - mvn --version
  - rustc --version
  - cargo --version
build_script:
  - mvn --batch-mode clean package -DskipTests
test_script:
  - mvn --batch-mode clean package
cache:
  - C:\Users\appveyor\.m2
